version: "3.8"

services:

  postgres:
    ports:
      - "5432:5432"

  backend:
    volumes:
      - ./backend/app:/app
    build:
      context: ./backend
      dockerfile: backend.dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
